const logger = require('winston');
const jwt = require('jsonwebtoken');
var config = require('../config/development');

/**
  This function validates if the user that requests a service have
  the right privilege to use it. The token is generated by the auth
  service at route /api/ (it uses POST and GET)

*/
function isAuthenticated(req, res, next) {

  // check header or url parameters or post parameters for token

  var token = req.query.token || req.body.token || req.headers['x-access-token'];
  // decode token
  if (token) {

    // verifies secret and checks exp
    jwt.verify(token, config.secret.key, (err, decoded) => {
      if (err) {
        logger.error(err);
        return res.status(403).json({
          success: false,
          message: 'Failed to authenticate token.'
        });
      } else {
        // if everything is good, save to request for use in other routes
        req.decoded = decoded;
        next();
      }
    });

  } else {
    return res.status(403).send({
      success: false,
      message: 'No token provided.'
    });

  }
};

module.exports = isAuthenticated;